// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type KnownLanguages int32

const (
	KnownLanguages_ENGLISH KnownLanguages = 0
	KnownLanguages_SPANISH KnownLanguages = 1
)

var KnownLanguages_name = map[int32]string{
	0: "ENGLISH",
	1: "SPANISH",
}

var KnownLanguages_value = map[string]int32{
	"ENGLISH": 0,
	"SPANISH": 1,
}

func (x KnownLanguages) String() string {
	return proto.EnumName(KnownLanguages_name, int32(x))
}

func (KnownLanguages) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type TestEvent struct {
	// Types that are valid to be assigned to Event:
	//	*TestEvent_EventA
	//	*TestEvent_EventB
	Event                isTestEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestEvent) Reset()         { *m = TestEvent{} }
func (m *TestEvent) String() string { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()    {}
func (*TestEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}
func (m *TestEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEvent.Unmarshal(m, b)
}
func (m *TestEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEvent.Marshal(b, m, deterministic)
}
func (m *TestEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEvent.Merge(m, src)
}
func (m *TestEvent) XXX_Size() int {
	return xxx_messageInfo_TestEvent.Size(m)
}
func (m *TestEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TestEvent proto.InternalMessageInfo

type isTestEvent_Event interface {
	isTestEvent_Event()
}

type TestEvent_EventA struct {
	EventA *EventA `protobuf:"bytes,1,opt,name=eventA,proto3,oneof"`
}
type TestEvent_EventB struct {
	EventB *EventB `protobuf:"bytes,2,opt,name=eventB,proto3,oneof"`
}

func (*TestEvent_EventA) isTestEvent_Event() {}
func (*TestEvent_EventB) isTestEvent_Event() {}

func (m *TestEvent) GetEvent() isTestEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *TestEvent) GetEventA() *EventA {
	if x, ok := m.GetEvent().(*TestEvent_EventA); ok {
		return x.EventA
	}
	return nil
}

func (m *TestEvent) GetEventB() *EventB {
	if x, ok := m.GetEvent().(*TestEvent_EventB); ok {
		return x.EventB
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TestEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TestEvent_OneofMarshaler, _TestEvent_OneofUnmarshaler, _TestEvent_OneofSizer, []interface{}{
		(*TestEvent_EventA)(nil),
		(*TestEvent_EventB)(nil),
	}
}

func _TestEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TestEvent)
	// event
	switch x := m.Event.(type) {
	case *TestEvent_EventA:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EventA); err != nil {
			return err
		}
	case *TestEvent_EventB:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EventB); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TestEvent.Event has unexpected type %T", x)
	}
	return nil
}

func _TestEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TestEvent)
	switch tag {
	case 1: // event.eventA
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventA)
		err := b.DecodeMessage(msg)
		m.Event = &TestEvent_EventA{msg}
		return true, err
	case 2: // event.eventB
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventB)
		err := b.DecodeMessage(msg)
		m.Event = &TestEvent_EventB{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TestEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TestEvent)
	// event
	switch x := m.Event.(type) {
	case *TestEvent_EventA:
		s := proto.Size(x.EventA)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TestEvent_EventB:
		s := proto.Size(x.EventB)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EventA struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At                   int64                `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Language             KnownLanguages       `protobuf:"varint,4,opt,name=language,proto3,enum=test.KnownLanguages" json:"language,omitempty"`
	Message              *EventA_InnerMessage `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventA) Reset()         { *m = EventA{} }
func (m *EventA) String() string { return proto.CompactTextString(m) }
func (*EventA) ProtoMessage()    {}
func (*EventA) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}
func (m *EventA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventA.Unmarshal(m, b)
}
func (m *EventA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventA.Marshal(b, m, deterministic)
}
func (m *EventA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventA.Merge(m, src)
}
func (m *EventA) XXX_Size() int {
	return xxx_messageInfo_EventA.Size(m)
}
func (m *EventA) XXX_DiscardUnknown() {
	xxx_messageInfo_EventA.DiscardUnknown(m)
}

var xxx_messageInfo_EventA proto.InternalMessageInfo

func (m *EventA) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventA) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventA) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *EventA) GetLanguage() KnownLanguages {
	if m != nil {
		return m.Language
	}
	return KnownLanguages_ENGLISH
}

func (m *EventA) GetMessage() *EventA_InnerMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type EventA_InnerMessage struct {
	Hello                string   `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventA_InnerMessage) Reset()         { *m = EventA_InnerMessage{} }
func (m *EventA_InnerMessage) String() string { return proto.CompactTextString(m) }
func (*EventA_InnerMessage) ProtoMessage()    {}
func (*EventA_InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1, 0}
}
func (m *EventA_InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventA_InnerMessage.Unmarshal(m, b)
}
func (m *EventA_InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventA_InnerMessage.Marshal(b, m, deterministic)
}
func (m *EventA_InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventA_InnerMessage.Merge(m, src)
}
func (m *EventA_InnerMessage) XXX_Size() int {
	return xxx_messageInfo_EventA_InnerMessage.Size(m)
}
func (m *EventA_InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventA_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventA_InnerMessage proto.InternalMessageInfo

func (m *EventA_InnerMessage) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

type OuterMessage struct {
	Hola                 string   `protobuf:"bytes,1,opt,name=hola,proto3" json:"hola,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OuterMessage) Reset()         { *m = OuterMessage{} }
func (m *OuterMessage) String() string { return proto.CompactTextString(m) }
func (*OuterMessage) ProtoMessage()    {}
func (*OuterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}
func (m *OuterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterMessage.Unmarshal(m, b)
}
func (m *OuterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterMessage.Marshal(b, m, deterministic)
}
func (m *OuterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterMessage.Merge(m, src)
}
func (m *OuterMessage) XXX_Size() int {
	return xxx_messageInfo_OuterMessage.Size(m)
}
func (m *OuterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OuterMessage proto.InternalMessageInfo

func (m *OuterMessage) GetHola() string {
	if m != nil {
		return m.Hola
	}
	return ""
}

type EventB struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At                   int64         `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Message              *OuterMessage `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EventB) Reset()         { *m = EventB{} }
func (m *EventB) String() string { return proto.CompactTextString(m) }
func (*EventB) ProtoMessage()    {}
func (*EventB) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}
func (m *EventB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventB.Unmarshal(m, b)
}
func (m *EventB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventB.Marshal(b, m, deterministic)
}
func (m *EventB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventB.Merge(m, src)
}
func (m *EventB) XXX_Size() int {
	return xxx_messageInfo_EventB.Size(m)
}
func (m *EventB) XXX_DiscardUnknown() {
	xxx_messageInfo_EventB.DiscardUnknown(m)
}

var xxx_messageInfo_EventB proto.InternalMessageInfo

func (m *EventB) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventB) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventB) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *EventB) GetMessage() *OuterMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.KnownLanguages", KnownLanguages_name, KnownLanguages_value)
	proto.RegisterType((*TestEvent)(nil), "test.TestEvent")
	proto.RegisterType((*EventA)(nil), "test.EventA")
	proto.RegisterType((*EventA_InnerMessage)(nil), "test.EventA.InnerMessage")
	proto.RegisterType((*OuterMessage)(nil), "test.OuterMessage")
	proto.RegisterType((*EventB)(nil), "test.EventB")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x97, 0xae, 0x7f, 0xdc, 0x59, 0x29, 0x12, 0x76, 0x51, 0xbd, 0x2a, 0x45, 0xa4, 0x0c,
	0x29, 0xb2, 0x3d, 0x41, 0x0b, 0xc3, 0x0d, 0xe7, 0x94, 0xcc, 0x17, 0xa8, 0x34, 0x6c, 0x85, 0x9a,
	0x8c, 0x26, 0x9b, 0x8f, 0xe9, 0x2b, 0x49, 0xd2, 0xac, 0xab, 0x78, 0xe9, 0xdd, 0xf7, 0xf1, 0xfd,
	0x7a, 0xce, 0xf9, 0x4a, 0x00, 0x24, 0x15, 0x32, 0x3d, 0x34, 0x5c, 0x72, 0x6c, 0x2b, 0x1d, 0x97,
	0x30, 0x7a, 0xa7, 0x42, 0x2e, 0x4e, 0x94, 0x49, 0x7c, 0x0f, 0x2e, 0x55, 0x22, 0x0b, 0x51, 0x84,
	0x92, 0xf1, 0xcc, 0x4f, 0x35, 0xaf, 0xc3, 0x6c, 0x39, 0x20, 0x26, 0xed, 0xb8, 0x3c, 0xb4, 0xfe,
	0x70, 0x79, 0xc7, 0xe5, 0xb9, 0x07, 0x8e, 0x56, 0xf1, 0x37, 0x02, 0xb7, 0x9d, 0x82, 0x03, 0xb0,
	0xaa, 0x52, 0xcf, 0x1f, 0x11, 0xab, 0x2a, 0x71, 0x08, 0xde, 0x89, 0x36, 0xa2, 0xe2, 0x4c, 0x0f,
	0x73, 0xc8, 0xd9, 0x2a, 0xb2, 0x90, 0xe1, 0x30, 0x42, 0xc9, 0x90, 0x58, 0x85, 0xc4, 0x8f, 0x70,
	0x55, 0x17, 0x6c, 0x77, 0x2c, 0x76, 0x34, 0xb4, 0x23, 0x94, 0x04, 0xb3, 0x49, 0xbb, 0xf7, 0x99,
	0xf1, 0x2f, 0xb6, 0x36, 0x91, 0x20, 0x1d, 0x85, 0xe7, 0xe0, 0x7d, 0x52, 0x21, 0xd4, 0x07, 0x8e,
	0x3e, 0xf4, 0xa6, 0x5f, 0x28, 0x5d, 0x31, 0x46, 0x9b, 0x97, 0x16, 0x20, 0x67, 0xf2, 0xf6, 0x0e,
	0xfc, 0x7e, 0x80, 0x27, 0xe0, 0xec, 0x69, 0x5d, 0x73, 0x73, 0x73, 0x6b, 0xe2, 0x18, 0xfc, 0xd7,
	0xa3, 0xbc, 0x50, 0x18, 0xec, 0x3d, 0xaf, 0x0b, 0x03, 0x69, 0x1d, 0x1f, 0x4c, 0xe9, 0xfc, 0x1f,
	0xa5, 0x1f, 0x2e, 0x15, 0x6c, 0x5d, 0x01, 0xb7, 0x15, 0xfa, 0xcb, 0xbb, 0xdb, 0xa7, 0x53, 0x08,
	0x7e, 0xff, 0x0c, 0x3c, 0x06, 0x6f, 0xb1, 0x79, 0x5a, 0xaf, 0xb6, 0xcb, 0xeb, 0x81, 0x32, 0xdb,
	0xb7, 0x6c, 0xa3, 0x0c, 0xfa, 0x70, 0xf5, 0x33, 0x98, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0x71, 0xad, 0x2f, 0x14, 0x02, 0x00, 0x00,
}
